const actions = {
  ADD_TODO: "ADD_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  TOGGLE_TODO: "FINISH_TODO",
  ADD_CATEGORY: "ADD_CATEGORY",
  REMOVE_CATEGORY: "REMOVE_CATEGORY",
  ADD_POMO: "ADD_POMO",  
  REMOVE_POMO: "REMOVE_POMO",
  TOGGLE_ACTIVE_TODO: "TOGGLE_ACTIVE_TODO",
  CLEAR_ACTIVE_TODO: "CLEAR_ACTIVE_TODO",
  SET_ACTIVE_CATEGORY: "SET_ACTIVE_CATEGORY",
  START_TIMER: "START_TIMER",
  PAUSE_TIMER: "PAUSE_TIMER",
  STOP_TIMER: "STOP_TIMER",
  SET_TIMER: "SET_TIMER",
  TIMER_FINISHED: "TIMER_FINISHED"
}

export default actions;